### ISSUE TITLE
Media buttons not working

### ISSUE THREAD

**Issue by Azkaas** [Aylur/dotfiles#17]
Has anyone been able to get the media buttons to work? They arent appearing for me

**Comment by thyeun** [comment]
Manually to force it appear and hard code it only control for spotify.

![Screenshot_2023-05-13-15-47-42_28923](https://github.com/Aylur/dotfiles/assets/1939446/320aa1ca-a019-47cd-bd6e-7f55d69bead2)

**Comment by Azkaas** [comment]
Thanks once again. Haha i guess you managed to figure it out in the end.

This is kind of out of topic, but are you also encountering the eww bug where the log just keeps growing into insane amount of size? I currently have set rm -rf on each boot, but i imagine its unhealthy for the SSD/HDD.

Do you by any change know how to deactive the logs on eww?

**Comment by thyeun** [comment]
Same here, cant solve it :(

**Comment by Azkaas** [comment]
Ah nice, it seems like you are not affected by the bug then :) Yeah that is the right file. For me it can reach like 30 GB in 1 day, and its a known bug

**Comment by thyeun** [comment]
i got modify the ```init``` file, but i dont think it is related.

You can try.
before
```
pkill eww
pkill myshell
eww daemon
```

after
```
pkill eww
pkill eww daemon
pkill myshell
eww daemon
```

**Comment by Azkaas** [comment]
You mean to just run all these commands in the terminal?
I just ran all of those commands, and restarted the computer, but still got the problem :/

**Comment by thyeun** [comment]
no, include in your ```init``` file. this file inside your ```~/.config/eww/scripts/```

deleted also your .log file that related with ```EWW```

**Comment by Azkaas** [comment]
Thanks for the clarification :)

Still doesnt solve the problem though. I hope the devs of eww fixes the bug soon... Seems like quite a few people have talked about it on their github

**Comment by thyeun** [comment]
Not sure, but i'm not facing ```eww``` .log file size increasing issue. :)

**Comment by Aylur** [comment]
type
````bash
pkill myshell
.config/eww/scripts/myshell/myshell --eww
````
does any error popup?

**Comment by thyeun** [comment]
i got no popup error

as you can see from below image.
![Screenshot_2023-05-15-21-58-21_4306](https://github.com/Aylur/dotfiles/assets/1939446/19ae32c2-9d99-4040-83be-cfad36d714c5)

let me further explain.
If you ```pkill myshell```, you only will get malfunction that related with function of .js script. (like apps_launcher not function)

```.config/eww/scripts/myshell/myshell --eww```, this one will reload the ```myshell``` and reload all the related directory in ```.cache/aylur```

p/s : if you want to see ```myshell``` error, you can run ```gjs -m myshell``` in terminal (make sure dont ```pkill myshell```). If you get no error by using ```gjs -m myshell```, meaning that your .js script are fine and workable.

**Comment by Aylur** [comment]
I recommend pkilling myshell first so it won't complain about the notification daemon already running
````bash
# these are the same
~/.config/eww/scripts/myshell/myshell --eww
# and
cd ~/.config/eww/scripts/myshell/myshell
gjs -m myshell
````

anyway I think I fixed the app launcher and I think this issue was also causing the media player to not show up

**Comment by Aylur** [comment]
what is the output of `eww get media` ?

**Comment by thyeun** [comment]
@Aylur Not sure how is the .js structure design from you, but some how the file ```media.json``` never push into ```.cache``` and create it, it is different from what you done on others (ie: notification.json, network.json and etc)

**Comment by Aylur** [comment]
what is the output of this?
````bash
dbus-send --session \
  --dest=org.freedesktop.DBus \
  --type=method_call \
  --print-reply /org/freedesktop/DBus \
  org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2
````

**Comment by thyeun** [comment]
@Aylur Below is the output of the cli 

```
dbus-send --session \
  --dest=org.freedesktop.DBus \
  --type=method_call \
  --print-reply /org/freedesktop/DBus \
  org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2
```
![Screenshot_2023-05-16-01-18-43_9604](https://github.com/Aylur/dotfiles/assets/1939446/f6ce721e-08b8-4218-a6a9-864315b88e43)

**Comment by Aylur** [comment]
is there no warning or error relating media.js if you do
````bash
~/.config/eww/scripts/init
````

**Comment by thyeun** [comment]
Below image show the ```init``` result.

![Screenshot_2023-05-16-01-29-11_11139](https://github.com/Aylur/dotfiles/assets/1939446/139f9e81-2281-466f-8972-4d8d11062cd2)

**Comment by thyeun** [comment]
Have to continue tomorrow, here already 2am, and thank you for your hard work

**Comment by thyeun** [comment]
@Aylur I noticed something as below might related with the media player not appear.

From the file ```~/.config/eww/scripts/yuck/windows/vbar.yuck```

```line 26, 44```, if remove the ```null```, the media player will appear two icon ```next``` and ```previous```. but not sure it is related or not.

**Comment by Aylur** [comment]
I pushed an update, can you try this again?
````
git clone https://github.com/Aylur/dotfiles.git
cp dotfiles/.config/eww/scripts/myshell/apps.js ~/.config/eww/scripts/myshell/apps.js
~/.config/eww/scripts/init
````

**Comment by thyeun** [comment]
@Aylur New update is for the apps right? If yes, done. 

but the media player still not appear.

**Comment by Aylur** [comment]
If there is no error or warning on myshell.js I have no idea what could be the problem.

**Comment by thyeun** [comment]
@Aylur After restart  laptop and login, the media player wont appear, but if i manually re-run ```gjs -m myshell --eww``` before i start/fire up ```spotify```,  media player wont appear also. And by using this step, the ```media.json``` in ```.cache``` still empty.

if i restart laptop and login, the media player wont appear, but if i start ```spotify``` and re-run ```gjs -m myshell --eww```, than the media player will appear, so what goes wrong here? And by using this step, the media.json in ```.cache``` will have all the info

**Comment by thyeun** [comment]
@Aylur Something to know, without open ```spotify```, the media player will appear on the bar? 

or 

Need to open ```spotify``` first, than only the media player appear on the bar?

**Comment by Aylur** [comment]
by default if there is no media player, then the widget shouldn't be visible, it should only appear when there are 1 or more media players running

**Comment by thyeun** [comment]
@Aylur My current situation is after open ```spotify``` and manually trigger/run the command ```gjs -m myshell --eww``` one more time (even ```init``` already run) than only the media player visible.

**Comment by Aylur** [comment]
Without any warnings or errors from the logs I can't help you

**Comment by thyeun** [comment]
@Aylur After your latest update for the ```async spawn```, the right side icon appear faster and no need relogin to get the icon appear (sometime need it). 

But for the media player automatically appear still not working, and of cause, there was no error, that why cant figure out why yours are possible to be automatically show out, and my was not? =.=
