### ISSUE TITLE
cat image not appearing in run launcher and wezterm not opening 

### ISSUE THREAD

**Issue by vs66388** [Aylur/dotfiles#21]
sorry if this question is dumb but i am a newbie and just started using window managers first of all the cat is not visible in run menu wezterm worked after installing font and zsh but second issue it vluetooth not visible in systry and empty patch is thier and secondly fi icons comes under media tray icons are missing from powermenu tray too

**Comment by thyeun** [comment]
@vs66388 for the cat image not appear on your launcher, there are few things you need to check.

1. Check the file ```~/.config/eww/scss/variables.scss```. Look for the first line ```$assets: '/home/demeter/.config/eww/assets/';```, you need to change the path according to your correct right path.
2.  Open up your file manager and go to ```~/.config/eww/assets``` folder, and look for ```wallpaper.png``` either the file is ```symlink``` to ```/home/demeter/.config/background```, if yes, you have to replace it with one of the file from folder ```~/.config/eww/assets/wallpapers/``` with same file name.

For bluetooth visible in you ```eww bar```, you have to install the dependency of ```gnome-bluetooth-3.0``` (you can find out all the related dependencies for this ```eww bar``` on ```readme.md```).

the ```fi``` on the media player is wrong codepoint from the font ```ubuntu nerd font```, you have to change the correct one from the ```nerd font cheatsheet```. Change it from the file ```~/.config/eww/scripts/myshell/main.js```. You will see the ```fi``` in that file, so just replace the correct one from the ```nerd font cheatsheet```.

**Comment by vs66388** [comment]
> 

icons are fixed i replaced themn from cheat sheet but still no wallpaper in run menu and powermenu icons are missing too

**Comment by vs66388** [comment]
> 

everything is fine now but in powermenu icons are not visible just empty boxs

**Comment by thyeun** [comment]
@vs66388 for the ```powermenu``` you still not follow the change on the ```variables.scss```, all that icon link to the ```$assets``` path, if you path are correct, all the ```powermenu``` icons will appear.

for the ```launcher search``` icon as you see is ```fl```, you have to change it in the file ```~/.config/eww/yuck/windows/app_launcher.yuck```.

**Comment by vs66388** [comment]
> 

i fixed the path in ~/.config/eww/scss/variables.scss and after creating newsymlink llauncher was fine but powermenu icons are still missing

**Comment by thyeun** [comment]
@vs66388 show me your code for ```variables.scss```, and ```powermenu.scss```.

**Comment by vs66388** [comment]
this
[powermenu](https://drive.google.com/file/d/1IPqvlpTw33K0y0YBc19sY6qoGhCUXzDZ/view?usp=share_link) [varibles](https://drive.google.com/file/d/1iag0xC8RwxUAzgtx5Nro5-V1Zh_HvnTk/view?usp=share_link)

**Comment by thyeun** [comment]
@vs66388 Check back the original ```powermenu.scss``` file. look like yours one is different.

**Comment by thyeun** [comment]
@vs66388 Show a screenshot of your bar that you want to reduce gaps.

**Comment by vs66388** [comment]
no the one that come with the config i wanna reduce the flaoting gaps
and i tried fixing it but nothing happened
